Watching for file changes with StatReloader
Internal Server Error: /pricing_api/skudetail/
Traceback (most recent call last):
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/fields.py", line 446, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/fields.py", line 96, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'VmSizes' object has no attribute 'benchmark'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/logapriya/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/Users/logapriya/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/logapriya/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/logapriya/env/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 509, in to_representation
    attribute = field.get_attribute(instance)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/fields.py", line 479, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `benchmark` on serializer `VmSkuListSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `VmSizes` instance.
Original exception text was: 'VmSizes' object has no attribute 'benchmark'.
"GET /pricing_api/skudetail/ HTTP/1.1" 500 145
/Users/logapriya/Tivona/pricing_api/pricing_data/pricing_api/vm_sku_serializer.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /pricing_api/skudetail/
Traceback (most recent call last):
  File "/Users/logapriya/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/Users/logapriya/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/logapriya/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/logapriya/env/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
  File "/Users/logapriya/env/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 1052, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 1148, in get_field_names
    assert field_name in fields, (
AssertionError: The field 'benchmark' was declared on serializer VmSkuListSerializer, but has not been included in the 'fields' option.
"GET /pricing_api/skudetail/ HTTP/1.1" 500 145
Internal Server Error: /pricing_api/skudetail/
Traceback (most recent call last):
  File "/Users/logapriya/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/Users/logapriya/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/logapriya/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/logapriya/env/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
  File "/Users/logapriya/env/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 1052, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 1148, in get_field_names
    assert field_name in fields, (
AssertionError: The field 'benchmark' was declared on serializer VmSkuListSerializer, but has not been included in the 'fields' option.
"GET /pricing_api/skudetail/ HTTP/1.1" 500 145
Internal Server Error: /pricing_api/skudetail/
Traceback (most recent call last):
  File "/Users/logapriya/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/Users/logapriya/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/logapriya/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/logapriya/env/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
  File "/Users/logapriya/env/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 1052, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 1148, in get_field_names
    assert field_name in fields, (
AssertionError: The field 'benchmark' was declared on serializer VmSkuListSerializer, but has not been included in the 'fields' option.
"GET /pricing_api/skudetail/ HTTP/1.1" 500 145
Internal Server Error: /pricing_api/skudetail/
Traceback (most recent call last):
  File "/Users/logapriya/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/Users/logapriya/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/logapriya/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/logapriya/env/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
  File "/Users/logapriya/env/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 1052, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "/Users/logapriya/env/lib/python3.10/site-packages/rest_framework/serializers.py", line 1148, in get_field_names
    assert field_name in fields, (
AssertionError: The field 'benchmark' was declared on serializer VmSkuListSerializer, but has not been included in the 'fields' option.
"GET /pricing_api/skudetail/ HTTP/1.1" 500 145
Watching for file changes with StatReloader
"GET /pricing_api/skudetail/ HTTP/1.1" 200 892564
"GET /pricing_api/skudetail/Standard_A0/eastus HTTP/1.1" 200 6891
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 179
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 179
Not Found: /pricing_api
"GET /pricing_api HTTP/1.1" 404 179
"GET /pricing_api/regions HTTP/1.1" 200 7278
/home/shravan/Documents/pricing/pricing_api/pricing_data/pricing_data/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/shravan/Documents/pricing/pricing_api/pricing_data/pricing_data/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/shravan/Documents/pricing/pricing_api/pricing_data/pricing_data/settings.py changed, reloading.
Watching for file changes with StatReloader
"GET /pricing_api/vm_tiers HTTP/1.1" 200 52
"GET /pricing_api/skudetail HTTP/1.1" 301 0
"GET /pricing_api/skudetail/ HTTP/1.1" 200 846805
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2177
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2228
Not Found: /pricing_api/
"GET /pricing_api/ HTTP/1.1" 404 4438
Not Found: /favicon.ico
Internal Server Error: /pricing_api/regions
Traceback (most recent call last):
  File "/home/shravan/Documents/pricing/pricing_api/pricing_data/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column pricing_api_region.display_name does not exist
LINE 1: ...ng_api_region"."id", "pricing_api_region"."name", "pricing_a...
                                                             ^
HINT:  Perhaps you meant to reference the column "pricing_api_region.displayname".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/shravan/Documents/pricing/pricing_api/pricing_data/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/shravan/Documents/pricing/pricing_api/pricing_data/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shravan/Documents/pricing/pricing_api/pricing_data/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/shravan/Documents/pricing/pricing_api/pricing_data/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/shravan/Documents/pricing/pricing_api/pricing_data/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/shravan/Documents/pricing/pricing_api/pricing_data/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/shravan/Documents/pricing/pricing_api/pricing_data/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/shravan/Documents/pricing/pricing_api/pricing_data/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/shravan/Documents/pricing/pricing_api/pricing_data/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/home/shravan/Documents/pricing/pricing_api/pricing_data/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 40, in list
    page = self.paginate_queryset(queryset)
  File "/home/shravan/Documents/pricing/pricing_api/pricing_data/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 171, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "/home/shravan/Documents/pricing/pricing_api/pricing_data/venv/lib/python3.10/site-packages/rest_framework/pagination.py", line 395, in paginate_queryset
    return list(queryset[self.offset:self.offset + self.limit])
  File "/home/shravan/Documents/pricing/pricing_api/pricing_data/venv/lib/python3.10/site-packages/django/db/models/query.py", line 394, in __iter__
    self._fetch_all()
  File "/home/shravan/Documents/pricing/pricing_api/pricing_data/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/shravan/Documents/pricing/pricing_api/pricing_data/venv/lib/python3.10/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "/home/shravan/Documents/pricing/pricing_api/pricing_data/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/home/shravan/Documents/pricing/pricing_api/pricing_data/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/shravan/Documents/pricing/pricing_api/pricing_data/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/shravan/Documents/pricing/pricing_api/pricing_data/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/shravan/Documents/pricing/pricing_api/pricing_data/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/shravan/Documents/pricing/pricing_api/pricing_data/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/shravan/Documents/pricing/pricing_api/pricing_data/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column pricing_api_region.display_name does not exist
LINE 1: ...ng_api_region"."id", "pricing_api_region"."name", "pricing_a...
                                                             ^
HINT:  Perhaps you meant to reference the column "pricing_api_region.displayname".

"GET /pricing_api/regions HTTP/1.1" 500 167927
object instance creation for vmsku started at 2023-05-24 09:35:22.245360 hours!
finished loading sku objects with the values at 2023-05-24 09:37:33.780287 hours!
object instance creation for vmsku started at 2023-05-24 09:56:16.597909 hours!
finished loading sku objects with the values at 2023-05-24 09:58:26.698117 hours!
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2177
object instance creation for vmsku started at 2023-05-25 12:57:57.740701 hours!
finished loading sku objects with the values at 2023-05-25 12:59:04.072207 hours!
object instance creation for vmsku started at 2023-05-26 04:06:17.781218 hours!
finished loading sku objects with the values at 2023-05-26 04:08:14.747121 hours!
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2177
Not Found: /pricing_api/
"GET /pricing_api/ HTTP/1.1" 404 4438
"GET /pricing_api/regions HTTP/1.1" 200 7278
Not Found: /pricing_api/
"GET /pricing_api/ HTTP/1.1" 404 4438
"GET /pricing_api/vm_tiers HTTP/1.1" 200 52
Not Found: /pricing_api/
"GET /pricing_api/ HTTP/1.1" 404 4438
"GET /pricing_api/skudetail/ HTTP/1.1" 200 836603
